import { Header } from '@/components/Header/Header'
import './global.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
 title: 'KONABOS CHARTS',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: {
 children: React.ReactNode
}) {
 return (
  <html lang="en">
   <body className={inter.className}>{children}</body>
  </html>
 )
}
